AuthorName: canyie
Categories:
    - Xposed
CurrentVersion: "1.0"
CurrentVersionCode: 1
Description: <p>Initial release</p>
IssueTracker: ""
Name: SettingsFirewall 设置防睛眼
SourceCode: https://github.com/Xposed-Modules-Repo/top.canyie.settingsfirewall
Summary: Block apps from accessing system settings. 阻止应用偷看你的系统设置。
WebSite: ""
